[[session]]
name = "🏠 Home"
path = "~"
startup_command = "clear && fastfetch"

[[session]]
name = "🗒️ Scratch"
path = "~/Scratch"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "🛠️ Dotfiles"
path = "~/.dotfiles"
# startup_command = "nvim . '+Telescope find_files hidden=true'; clear"
startup_command = "clear && eza -a --icons=always && git status"

[[session]]
# TODO Change Hyprland session to "\e[38;2;35;88;100m\e[0m Hyprland"
name = " Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "nvim hyprland.conf; clear"

[[session]]
name = " NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "nvim . '+Telescope find_files'; clear"

[[session]]
name = " Emacs"
path = "~/.dotfiles/.doom.d"
startup_command = "nvim config.el; clear"

[[session]]
name = "⌨️ Kanata"
path = "~/.dotfiles/kanata"
startup_command = "nvim kanata.kdb; clear"

[[session]]
# TODO: Change Waybar session to "\e[38;2;255;190;8m\e[0m Waybar"
name = " Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "nvim config.jsonc; clear"

[[session]]
name = "🔎 Rofi"
path = "~/.dotfiles/.config/rofi"
startup_command = "nvim config.rasi; clear"

[[session]]
# TODO: Fix  not working
name = " Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml; clear"

[[session]]
name = "⚙️ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "nvim .; clear"

[[session]]
name = "🏦 Vault"
path = "~/Vault"
startup_command = "nvim 1741211101-main-hub.md '+ObsidianQuickSwitch'; clear"

[[session]]
name = "📓 Notes"
path = "~/Vault/notes"
startup_command = "clear && eza --tree --icons=always"

[[session]]
name = "📥 Downloads"
path = "~/Downloads"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "📄 Documents"
path = "~/Documents"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "📹 Videos"
path = "~/Videos"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "🎵 Music"
path = "~/Music"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "📸 Pictures"
path = "~/Pictures"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "📖 Dictionary"
path = "/home/allisnull/.config/nvim/spell"
startup_command = "nvim .; clear"

[[session]]
name = "📚 Library"
path = "~/Documents/Library"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "🧠 Brain"
path = "~/Programming/Brain/brain-musik"
startup_command = "~/.config/sesh/scripts/flutter.sh"

[[session]]
name = "🪹 Birds Nest"
path = "~/Programming/BirdsNest/birds_nest"
startup_command = "~/.config/sesh/scripts/flutter.sh"
