[[session]]
name = "🏠 Main"
path = "~"
startup_command = "clear && fastfetch"

[[session]]
name = "🗒️ Scratch"
path = "~/Scratch"

[[session]]
name = "🛠️ Dotfiles"
path = "~/.dotfiles"
# startup_command = "nvim . '+Telescope find_files hidden=true'; clear"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = " NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "nvim . '+Telescope find_files'; clear"

[[session]]
name = "⚙️ Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "nvim sesh.toml; clear"

[[session]]
name = "⌨️ Kanata"
path = "~/.dotfiles/kanata"
startup_command = "nvim kanata.kdb; clear"

[[session]]
name = "🔎 Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "nvim config.jsonc; clear"

[[session]]
name = "🪟 Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "nvim hyprland.conf; clear"

[[session]]
name = "⚙️ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "nvim .; clear"

[[session]]
name = "🏦 Vault"
path = "~/Vault"

[[session]]
name = "📓 Notes"
path = "~/Notes"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "🧠 Brain"
path = "~/Programming/Brain/brain-musik"
startup_command = "~/.config/sesh/scripts/brain.sh"

[[session]]
name = "📖 Dictionary"
path = "/home/allisnull/.cache/nvim/ltex"
startup_command = "nvim en-US.txt; clear"

[[session]]
name = "📥 Downloads"
path = "~/Downloads"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "📄 Documents"
path = "~/Documents"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "📹 Videos"
path = "~/Videos"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "🎵 Music"
path = "~/Music"
startup_command = "clear && eza -a --icons=always"

[[session]]
name = "📸 Pictures"
path = "~/Pictures"
startup_command = "clear && eza -a --icons=always"
