[[session]]
name = "🏠 Home"
path = "~"

[[session]]
name = "🗒️ Scratch"
path = "~/Scratch"
startup_command = "c && lsa"

[[session]]
name = "🛠️ Dotfiles"
path = "~/.dotfiles"
# startup_command = "v . '+Telescope find_files hidden=true'; clear"
startup_command = "c && lsa && gs"

[[session]]
name = "#[fg=#56bce1]#[fg=#000000] Hyprland"
path = "~/.dotfiles/.config/hypr"
startup_command = "v hyprland.conf;c"

[[session]]
name = "#[fg=#83b06c]#[fg=#000000] NeoVim"
path = "~/.dotfiles/.config/nvim"
startup_command = "v . '+Telescope find_files';c"

[[session]]
name = "#[fg=#83b06c]#[fg=#000000] NvimPager"
path = "~/.dotfiles/.config/nvimpager"
startup_command = "v init.lua '+AutoSession restore';c"

[[session]]
name = "#[fg=#7c65b4]#[fg=#000000] Emacs"
path = "~/.dotfiles/.emacs.legacy"
startup_command = "v init.el;c"

[[session]]
name = "⌨️ Kanata"
path = "~/.dotfiles/.config/kanata"
startup_command = "v kanata.kbd;c"

[[session]]
name = "#[fg=#f6be41]#[fg=#000000] Waybar"
path = "~/.dotfiles/.config/waybar"
startup_command = "v config.jsonc;c"

[[session]]
name = "🔎 Rofi"
path = "~/.dotfiles/.config/rofi"
startup_command = "v config.rasi;c"

[[session]]
# TODO: Fix  not working
name = "󰕮 Sesh"
path = "~/.dotfiles/.config/sesh"
startup_command = "v sesh.toml;c"

[[session]]
name = "⚙️ Zsh"
path = "~/.dotfiles/.zsh/config"
startup_command = "v .;c"

[[session]]
name = "🏦 Vault"
path = "~/Vault"
startup_command = "vault;c"

[[session]]
name = " Trading"
path = "~/Programming/Trading"
startup_command = "conda activate quant && c && lsa"

[[session]]
name = "📓 Notes"
path = "~/Vault/notes"
startup_command = "c && lst"

[[session]]
name = "📥 Downloads"
path = "~/Downloads"
startup_command = "y;c"

[[session]]
name = "📄 Documents"
path = "~/Documents"
startup_command = "y;c"

[[session]]
name = "📹 Videos"
path = "~/Videos"
startup_command = "y;c"

[[session]]
name = "🎵 Music"
path = "~/Music"
startup_command = "y;c"

[[session]]
name = "📸 Pictures"
path = "~/Pictures"
startup_command = "y;c"

[[session]]
name = "📚 Library"
path = "~/Documents/Library"
startup_command = "y;c"

[[session]]
name = "#[fg=#4000c0]#[fg=#000000] Documentation"
path = "/usr/share/doc"
startup_command = "y;c"

[[session]]
name = "📖 Dictionary"
path = "/home/allisnull/.config/nvim/spell"
startup_command = "v .;c"

[[session]]
name = "🔧 Settings"
path = "~/Documents/Settings"
startup_command = "c && lsa"

# Projects
[[session]]
name = "#[fg=#660606]󰕍#[fg=#000000] Zsh-Undo-Dir"
path = "~/.dotfiles/.zsh/plugins/zsh-undo-dir"
startup_command = "v zsh-undo-dir.plugin.zsh;c"

[[session]]
name = "🚀 HandmadeHero"
path = "~/Programming/LearningCS/HandmadeHero/"
startup_command = "v code/main.c '+vert Compile build/handmade';c"

[[session]]
name = "🧑🏽‍🌾 TheFarmerWasReplaced"
path = "~/.steam/steam/steamapps/compatdata/2060160/pfx/drive_c/users/steamuser/AppData/LocalLow/TheFarmerWasReplaced/TheFarmerWasReplaced/Saves/TheFarmerWasReplaced"
startup_command = "v main.py '+lua vim.diagnostic.enable(false)' '+Telescope find_files';c"

[[session]]
name = "🧠 Brain"
path = "~/Programming/work/Brain/brainmusik-mobile/"
startup_command = "~/.config/sesh/scripts/flutter.sh"

[[session]]
name = "🪹 Birds Nest"
path = "~/Programming/work/BirdsNest/birds_nest"
startup_command = "~/.config/sesh/scripts/flutter.sh"

[[session]]
name = "🏅 JuegazoPR"
path = "~/Programming/Work/JuegazoPR/juegazo-pr"
startup_command = "~/.config/sesh/scripts/next-js.sh"

[[session]]
name = " JuegazoPR Admin"
path = "~/Programming/Work/JuegazoPR/juegazo-pr-admin"
startup_command = "~/.config/sesh/scripts/next-js.sh"
