# Git
alias gi="git init && git commit --allow-empty -m 'init'"
alias ga="git add"
alias gaa="git add ."
alias gau="git add -u"
alias gb="git branch -a"
alias gbd="git branch -D"
alias gsw="git switch -c $@"
alias gc="git commit"
alias gcm="git commit -m"
alias gcma="git commit -am"
alias gcmp="git commit -m $@ && git push"
alias gca='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit --amend --no-edit --date="$(git log -n 1 --format=%aD)" --allow-empty'
alias gcaa='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit -a --amend --no-edit --date="$(git log -n 1 --format=%aD)" --allow-empty'
alias gcam='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit --amend -m --date="$(git log -n 1 --format=%aD)" --allow-empty'
alias gcaam='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit -a --amend -m --date="$(git log -n 1 --format=%aD)" --allow-empty'
alias grn='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit --amend --date="$(git log -n 1 --format=%aD)" --allow-empty'
alias gcap='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit --amend --no-edit --date="$(git log -n 1 --format=%aD)" --allow-empty && git push --force'
alias gcaap='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit -a --amend --no-edit --date="$(git log -n 1 --format=%aD)" --allow-empty && git push --force'
alias gcamp='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit --amend --date="$(git log -n 1 --format=%aD)" --allow-empty && git push --force'
alias gcaamp='export GIT_COMMITTER_DATE="$(git log -n 1 --format=%aD)" && git commit -a --amend --date="$(git log -n 1 --format=%aD)" --allow-empty && git push --force'
alias gch="git checkout"
alias gchf="git checkout --force"
alias gcho="git checkout --orphan"
alias gcl="git clone"
alias gcld="git clone --depth=1"
alias gd="git diff --color=always"
alias gds="git diff --color=always --staged"
alias gdsa="git add . && git diff --color=always --staged"
alias gf="git fetch"
alias gfa="git fetch --all"
alias gl="git log --oneline --decorate --graph"
alias glf="git log -p -- $@"
alias gls="git ls-files --full-name | awk -F/ "\""{print $1}"\"" | sort -u"
alias gp="git push"
alias gpf="git push --force"
alias gpl="git pull"
alias gplf="git pull --force"
alias grm"git rm -f --cached"
alias grma"git rm . -r"
alias gs="git status"
alias gsh="git show --color=always"
alias gst="git stash"
alias gsti="git stash --include-untracked"
alias gstm="git stash -m"
alias gsta="git stash apply"
alias gstd="git stash drop"
alias gstc="git stash clear"
alias gstl="git stash list"
alias gstad="git stash apply && git stash drop"
alias grb="git rebase"
alias grbi="git rebase -i"
alias grbir="git rebase -i --root"
alias grbc="git rebase --continue"
alias grbs="git rebase --skip"
alias grba="git rebase --abort"
alias grs="git reset"
alias grsf="git checkout HEAD -- $@"
alias gdl="git reset --hard HEAD^"
alias gun="git reset --hard HEAD"
alias grm="git rm --cached -r $@"
alias grma="git rm --cached -r ."
alias greset="git fetch --all & git reset --hard origin/main"
alias gclean="git clean -f"
# TODO: Figure out local gitignore
# alias gig="git update-index --assume-unchanged $@"
# alias gigr="git update-index --no-assume-unchanged $@"
